[colours]
;NORD
background = #2e3440
background-alt = #3b4252
foreground = #e5e9f0
primary = #81a1c1
secondary = #88c0d0
tertiary = #b48ead
fourtiary = #a3be8c
fiftiary = #ebcb8b
sixtiary = #d08770
alert = #bf616a
disabled = #4c566a


[bar/qtile]
modules-left = xworkspaces date xwindow
modules-center = 
modules-right = playing backlight volume cpu memory wlan xkeyboard

bottom = false
fixed-center = true
width = 100%
height = 30px

tray-position = right 
tray-detached = false
tray-maxsize = 14

background = ${colours.background}
foreground = ${colours.primary}
line-size = 3
padding = 1
module-margin = 1
padding-right = 2
separator = /

font-0 = "Source Code Pro:style=Regular:size=11;0"
font-1 = "IBM Plex Sans:style=Regular:weight=Bold:size=11;0"
font-2 = "Material Design Icons:size=11;0"

; BACKLIGHT
[module/backlight]
type = internal/backlight
card = acpi_video0
enable_scroll = true
format = 󰖙 <label> <bar>
format-underline = ${colours.secondary}
format-foreground = ${colours.secondary}
bar-width = 10
bar-indicator = |
bar-fill = ─
bar-empty = ─

;CPU
[module/cpu]
type = internal/cpu
warn-percentage = 90
format = 󰚗 <label> <bar-load>
format-underline = ${colours.fourtiary}
format-foreground = ${colours.fourtiary}
bar-load-width = 10
bar-load-indicator = |
bar-load-fill = ─
bar-load-empty = ─

;DATE
[module/date]
type = internal/date
date = %Y-%m-%d%
time = %H:%M
format = 󰅐 <label>
format-underline = ${colours.sixtiary}
format-foreground = ${colours.sixtiary}
label = %date% - %time%
label-font = 2

;MEMORY
[module/memory]
type = internal/memory
interval = 5
warn-percentage = 90
format = 󰍛 <label> <bar-used>
format-underline = ${colours.fiftiary}
format-foreground = ${colours.fiftiary}
bar-used-indicator = |
bar-used-width = 10
bar-used-fill = ─
bar-used-empty = ─

;NETWORK
[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = 󰤭 %ifname% disconnected
label-connected-foreground = ${colours.sixtiary}
label-connected-underline = ${colours.sixtiary}
label-disconnected-foreground = ${colours.disabled}
[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = 󰤨 %essid%
[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-}

;VOLUME
[module/volume]
type = internal/pulseaudio
interval = 3
format-volume = 󰕾 <label-volume> <bar-volume>
format-volume-underline = ${colours.tertiary}
format-volume-foreground = ${colours.tertiary}
label-muted = 󰖁 muted
label-muted-foreground = ${colours.disabled}
bar-volume-width = 10
bar-volume-indicator = |
bar-volume-fill = ─
bar-volume-empty = ─

;KEYBOARD
[module/xkeyboard]
blacklist-0 = num lock
type = internal/xkeyboard
label-layout = 󰌌 %layout%
label-layout-foreground = ${colours.alert}
label-layout-underline = ${colours.alert}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colours.background}
label-indicator-background = ${colours.alert}

;WINDOW
[module/xwindow]
type = internal/xwindow
format-background = ${colours.background}
format-foreground = ${colours.foreground}
format-underline = ${colours.foreground}
label = 󱂬 %title%
label-maxlen = 60
label-empty = No windows available
label-empty-underline = ${colours.disabled}
label-empty-foreground = ${colours.disabled}

;WORKSPACES
[module/xworkspaces]
type = internal/xworkspaces
enable-scroll = true
reverse-scroll = true
label-active = %name%
label-active-background = ${colours.background-alt}
label-active-foreground = ${colours.foreground}
label-active-underline= ${colours.fiftiary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colours.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colours.disabled}
label-empty-padding = 1

;MRPIS
[module/playing]
type = custom/script
exec = ~/Source/polybar-scripts/polybar-scripts/player-mpris-tail/player-mpris-tail.py -f '󰎇 {artist} - {title}'
tail = true
format-underline = ${colours.primary}
click-left = ~/Source/polybar-scripts/polybar-scripts/player-mpris-tail/player-mpris-tail.py previous &
click-right = ~/Source/polybar-scripts/polybar-scripts/player-mpris-tail/player-mpris-tail.py next &
click-middle = ~/Source/polybar-scripts/polybar-scripts/player-mpris-tail/player-mpris-tail.py play-pause &
